KOA-5612 Switch to new colours
Skyscanner/backpack-foundations pull request #134
Opened 2022-10-04 10:51 UTC by marianeum

Remember to include the following changes:

- [x] `UNRELEASED.md` (See [How to write a good changelog entry](https://github.com/Skyscanner/backpack-foundations/blob/main/CHANGELOG_FORMAT.md))
- [x] `README.md`
- [x] Tests
- [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

2022-10-04 12:06 UTC, olliecurtis requested changes

2022-10-04 12:06 UTC, olliecurtis commented on packages/bpk-foundations-common/base/colors/aliases.json
> +    "SKY_BLUE_85": "#024DAF",
What is this token? I don't see it defined anywhere

2022-10-04 12:06 UTC, olliecurtis commented on packages/bpk-foundations-common/base/colors/aliases.json
> +    "DARK_SKY_85": "#154679",
Same here

2022-10-04 12:06 UTC, olliecurtis commented on packages/bpk-foundations-common/base/colors/aliases.json
> +    "NIGHT_GREY_00": "#0B121D",
Can we check with Adam on this one as I know he removed some aliases recently and this was one as we didn't need some of the additional ones

2022-10-04 16:01 UTC, marianeum commented on packages/bpk-foundations-common/base/colors/skeleton.json
> +      "value": "{!BLACK_ALPHA_20}"
sticking to not using aliases for these as per design

2022-10-05 09:57 UTC, olliecurtis approved these changes

2022-10-05 10:04 UTC, merged